### ISSUE TITLE
Elements in UI

### ISSUE THREAD

**Issue by raej15** [SCCapstone/pandas-capstone#106]
```[tasklist]
### Tasks
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/107
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/108
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/109
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/110
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/111
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/112
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/113
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/114
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/116
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/117
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/118
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/119
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/123
```
