### ISSUE TITLE
Resource Pages

### ISSUE THREAD

**Issue by raej15** [SCCapstone/pandas-capstone#116]
```[tasklist]
### Tasks
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/120
- [x] https://github.com/SCCapstone/pandas-capstone/issues/121
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/122
```
