### ISSUE TITLE
2. Users can create account

### ISSUE THREAD

**Issue by nataliecrawford** [SCCapstone/pandas-capstone#40]
```[tasklist]
### Tasks
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/76
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/72
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/73
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/74
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/75
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/104
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/105
```
