### ISSUE TITLE
4. User Profile

### ISSUE THREAD

**Issue by nataliecrawford** [SCCapstone/pandas-capstone#41]
```[tasklist]
### Tasks
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/83
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/84
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/85
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/86
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/87
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/88
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/89
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/124
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/125
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/126
```
