### ISSUE TITLE
10. Data Storage in Postgres

### ISSUE THREAD

**Issue by raej15** [SCCapstone/pandas-capstone#43]
```[tasklist]
### Tasks
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/100
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/101
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/102
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/103
```
