### ISSUE TITLE
8. Basic message function between users

### ISSUE THREAD

**Issue by nataliecrawford** [SCCapstone/pandas-capstone#46]
```[tasklist]
### Tasks
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/68
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/67
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/66
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/71
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/70
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/69
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/95
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/92
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/63
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/42
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/113
```
