### ISSUE TITLE
5. Settings

### ISSUE THREAD

**Issue by raej15** [SCCapstone/pandas-capstone#91]
```[tasklist]
### Tasks
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/48
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/45
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/47
- [ ] https://github.com/SCCapstone/pandas-capstone/issues/125
```
